version: '3.8'

services:
  redllm:
    build: .
    image: redllm:latest
    volumes:
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      python src/redllm/main.py
      --models "together_ai/deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free"
      --api-keys "${TOGETHER_API_KEY}"
      --judge-models "together_ai/deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free"
      --judge-keys "${TOGETHER_API_KEY}"
      --output "/app/output/report.csv"
      --details-dir "/app/output/details"
      --variations 6
      --max-jailbreaks 10
      --verbose 1